version: "3.8"
services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    container_name: db_bot
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_bot
