CREATE TABLE IF NOT EXISTS tg_chats (
        id BIGINT PRIMARY KEY,
        created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Таблица для хранения ссылок
CREATE TABLE IF NOT EXISTS links (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        url TEXT NOT NULL,
        description TEXT,
        updated_at TIMESTAMP WITHOUT TIME ZONE
);

-- Таблица для хранения фильтров
CREATE TABLE IF NOT EXISTS filters (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    link_id BIGINT REFERENCES links(id) ON DELETE CASCADE,
    filter TEXT NOT NULL
);

-- Таблица для хранения тегов (нормализованная структура)
CREATE TABLE IF NOT EXISTS tags (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    link_id BIGINT REFERENCES links(id) ON DELETE CASCADE,
    tag TEXT NOT NULL
);

-- Таблица для связи чатов и ссылок
CREATE TABLE IF NOT EXISTS tg_chat_links (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tg_chat_id BIGINT REFERENCES tg_chats(id) ON DELETE CASCADE,
    link_id BIGINT REFERENCES links(id) ON DELETE CASCADE
);

-- Индексы для ускорения запросов
CREATE INDEX idx_tg_chat_links_tg_chat_id ON tg_chat_links(tg_chat_id);
CREATE INDEX idx_tg_chat_links_link_id ON tg_chat_links(link_id);
CREATE INDEX idx_filters_filter ON filters(filter);
CREATE INDEX idx_tags_tag ON tags(tag);
