app:
  github:
    github-token: ${GITHUB_TOKEN} # env variable
    github-url: https://api.github.com/repos/
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}


scheduler:
  enable: true
  interval: 7000
  force-check-delay: PT10S


spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
