app:
  github:
    github-token: ${GITHUB_TOKEN:} # env variable
    github-url: https://api.github.com/repos/
  stackoverflow:
    key: ${SO_TOKEN_KEY:}
    access-token: ${SO_ACCESS_TOKEN:}
    stack-overflow-url: https://api.stackexchange.com/2.3
  link:
    telegram-bot-uri: "http://localhost:8080"
  database-access-type: orm



scheduler:
  enable: true
  interval: 15000
  force-check-delay: PT10S
  batch-size: 4


spring:
  application:
    name: Scrapper

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/scrapper_db
    username: postgres
    password: postgres

  liquibase:
    enabled: false

  jpa:
    #    hibernate:
    #      ddl-auto: validate
    #    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true


server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

#logging:
#  structured:
#    format:
#      file: ecs
#      console: ecs
#  level:
#    root: INFO

