app:
  github:
    github-token: ${GITHUB_TOKEN:} # env variable
    github-url: https://api.github.com/repos/
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
    stack-overflow-url: https://api.stackexchange.com/2.3/questions/
  link:
    telegram-bot-uri: "http://localhost:8080"


scheduler:
  enable: true
  interval: 7000
  force-check-delay: PT10S


spring:
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
