app:
  telegram-token: ${TELEGRAM_TOKEN}  # env variable
  link:
    scrapper-uri: "http://localhost:8081"
  topic: "updated-topic"

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379

  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      auto-offset-reset: earliest
      group-id: "consumer-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: backend.academy.bot.api.dto.request.LinkUpdate
#  # Полная конфигурация Redis
#  data:
#    redis:
#      host: ${REDIS_HOST:localhost}    # Или redis (если в одной docker сети)
#      port: ${REDIS_PORT:6380}         # Должен совпадать с внешним портом из docker-compose
#      password: ${REDIS_PASSWORD:redis} # Пароль из docker-compose
#      username: ${REDIS_USER:user}      # Пользователь из docker-compose
#      database: ${REDIS_DATABASE:0}
#      timeout: 5000                    # Таймаут подключения в ms
#      lettuce:
#        pool:
#          max-active: 8                # Максимальное количество соединений
#          max-idle: 8
#          min-idle: 2
#          max-wait: 2000               # Максимальное время ожидания соединения
       # shutdown-timeout: 100ms        # Таймаут при завершении
server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui


#logging:
#  structured:
#    format:
#      file: ecs
#      console: ecs
#  level:
#    root: INFO
