app:
  telegram-token: ${TELEGRAM_TOKEN}  # env variable
  link:
    scrapper-uri: "http://localhost:8081"
  topic: "updated-topic"
  topic-dlq: "dead-letter-queue"
  notification:
    mode: IMMEDIATE
    daily-digest-time: "10:36"


spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  cache:
    type: redis
    data:
      redis:
        host: localhost
        port: 6379

  kafka:
    bootstrap-servers: "localhost:29092"
    consumer:
      auto-offset-reset: earliest
      group-id: "consumer-group"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: backend.academy.bot.api.dto.request.LinkUpdate
    producer:
      client-id: "producer-DLQ"  # Изменено с group-chatId на client-chatId
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

webclient:
  timeouts:
    connect-timeout: 10s    # 10 секунды на подключение
    response-timeout: 10s   # 10 секунд на ответ
    global-timeout: 20s     # 10 секунд на весь запрос


#logging:
#  structured:
#    format:
#      file: ecs
#      console: ecs
#  level:
#    root: INFO
