app:
  telegram-token: ${TELEGRAM_TOKEN}  # env variable
  link:
    scrapper-uri: "http://localhost:8081"

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui


logging:
  structured:
    format:
      file: ecs
      console: ecs
  level:
    root: INFO
